--- 
android: 
  components: 
    - tools
    - platform-tools
    - tools
    - build-tools-30.0.3
    - android-30
    - extra-android-m2repository
before_install: 
  - "chmod +x gradlew"
jdk: oraclejdk8
language: android
script: 
  - "./gradlew build"
sudo: required
